name: Countinuos Making README.md

on:
  push:
    paths:
      - "**.md"
      - "!REAME.md"

jobs:
  post:
    name: "README rewrite"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: node src/makeReadme.mjs

      - name: add and commit
        uses: EndBug/add-and-commit@v7
        with:
          add: "README.md"
          default_author: user_info
          branch: main
          message: "Commit from GitHub Actions: README 업데이트"
          push: true
