name: Countinuos Making README.md

on:
  push:
    paths:
      - '**.md'
      - '!REAME.md'
    
jobs:
  steps:
    # 수정중...
    # - name: README rewrite
    #   runs-on: ubuntu-latest
    #   steps:
    #     - shell: bash
    #       run: 
    # - name: add and commit
    #   uses: EndBug/add-and-commit@v7
    #   with:
    #     add: 'README.md'
    #     author_name: RamiTae
    #     author_email: ramiTae.dev@gmail.com
    #     branch: main
    #     committer_name: RamiTae
    #     committer_email: ramiTae.dev@gmail.com
    #     default_author: RamiTae
    #     message: 'Commit from GitHub Actions: README 업데이트'
    #     push: true
