name: Countinuos Making README.md

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
    
jobs:
  steps:
    - name: README rewrite
    - name: add and commit
      # TODO: github action push트리거 수정 필요
      uses: EndBug/add-and-commit@v7
      with:
        add: 'README.md'
        author_name: RamiTae
        author_email: ramiTae.dev@gmail.com
        branch: main
        committer_name: RamiTae
        committer_email: ramiTae.dev@gmail.com
        default_author: RamiTae
        message: 'Commit from GitHub Actions: README 업데이트'
        push: true
